name: Create FenrirOS iso

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  download_artix:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: sudo bash download.sh
    - uses: actions/upload-artifact@v3
      with:
        name: download
        path: download/

  build_fenrir:
    runs-on: ubuntu-latest
    needs:
     - download_artix
    env:
      EDITION: runit
      EXTRA_PKGS: runit elogind-runit
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: download
          path: download/
      - run: sudo apt-get install linux-modules-5.15.0-1017-azure
      - run: sudo -E bash build.sh > iso/build.log
      - uses: actions/upload-artifact@v3
        with:
          name: iso
          path: iso/
      - uses: actions/upload-artifact@v3
        with:
          name: build.log
          path: iso/*
  
  publish:
    runs-on: ubuntu-latest
    needs: build_fenrir
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/download-artifact@v3
      - uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{secrets.GITHUB_TOKEN}}"
          automatic_release_tag: latest
          files: FenrirOS-runit.zip
          prerelease: false

