name: Create FenrirOS iso

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  download_artix:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: sudo bash download.sh
    - uses: actions/upload-artifact@v3
      with:
        name: download
        path: download/

  build_fenrir:
    runs-on: ubuntu-latest
    needs:
     - download_artix

    strategy:
      fail-fast: false
      matrix:
        include:
        - edition: openrc
          extra_pkgs: openrc elogind-openrc
        - edition: runit
          extra_pkgs: runit elogind-runit
        - edition: s6
          extra_pkgs: s6-base elogind-s6
        - edition: dinit
          extra_pkgs: dinit elogind-dinit

    env:
      EDITION: ${{ matrix.edition }}
      EXTRA_PKGS: ${{ matrix.extra_pkgs }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: download
          path: download/
      - run: sudo -E bash build.sh > build.log
      - uses: actions/upload-artifact@v3
        with:
          name: iso
          path: iso/
  
  publish:
    runs-on: ubuntu-latest
    needs: build_fenrir
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/download-artifact@v3
      - uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{secrets.GITHUB_TOKEN}}"
          automatic_release_tag: latest
          files: iso/*.iso
          prerelease: false

